# Generated by Django 4.0.6 on 2022-07-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectinfo',
            name='github',
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
