# Generated by Django 4.0.6 on 2022-07-14 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_projectinfo_demo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinfo',
            name='demo',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
