# Generated by Django 4.0.6 on 2022-07-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_projectinfo_demo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=200)),
                ('link', models.URLField(blank=True)),
                ('image', models.FileField(blank=True, upload_to='photos/')),
                ('show', models.BooleanField(default=False)),
            ],
        ),
    ]
