# Generated by Django 4.0.6 on 2022-07-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='image',
            field=models.FileField(blank=True, upload_to='photos/experiences'),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='image',
            field=models.FileField(blank=True, upload_to='photos/projects'),
        ),
    ]
