# Generated by Django 3.1.3 on 2023-01-10 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_experience_image_alter_projectinfo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='priority',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='priority',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='experience',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
